// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(WebAPI_DataContext))]
    partial class WebAPI_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Vehicle>().HasData(
                new Vehicle
                {
                    Id = 1,
                    Reg = "LPN791",
                    Make = "Mazda",
                    Model = "Rx8",
                    Colour = "Black",
                    Year = 2003

                }
            );
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Vehicle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Colour")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Make")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Model")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Reg")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Vehicle");
            });
#pragma warning restore 612, 618
        }
    }
}
